CREATE DATABASE sa_backend

CREATE TABLE CLIENT(
ID integer primary key not null AUTO_INCREMENT,
EMAIL varchar(50),
TELEPHONE varchar(15),
CREATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
MODIFICATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SENTIMENT(
ID integer primary key not null AUTO_INCREMENT,
TEXTE varchar(50),
TYPE varchar(10),
CLIENT_ID integer,
CONSTRAINT client_fk FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(ID)
);